version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
      day: "sunday"
    open-pull-requests-limit: 100
    target-branch: "master"
    groups:
      new-minor-only:
        update-types: [minor]
      new-patch-only:
        update-types: [patch]
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major