version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
      day: "sunday"
    target-branch: "master"
    open-pull-requests-limit: 0
    groups:
      patches:
        update-types:
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    allow:
      - dependency-name: "*"