version: '3.4'

services:
  app:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"

  development:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
    command: ["sh", "./scripts/run-dev.sh"]


  tests:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_dir: /app
    volumes:
      - .:/app
    command: ["sh", "./scripts/run-tests.sh"]
